sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shannerterman/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shannerterman/multi-docker npm test

after_success:
  - docker build -t shannerterman/multi-client ./client
  - docker build -t shannerterman/multi-nginx ./nginx
  - docker build -t shannerterman/multi-server ./server
  - docker build -t shannerterman/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push shannerterman/multi-client
  - docker push shannerterman/multi-nginx
  - docker push shannerterman/multi-server
  - docker push shannerterman/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-725177412300"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"